### PR TITLE
fix: Add accept option to merged config

### LINKED ISSUE #1340: accept 429 code not taken in account
With 0.14.0

lychee.toml contains

```toml
# Comma-separated list of accepted status codes for valid links.
accept = ["200", "206", "429"]
```

But results considers as errors 429 status codes

```sh

....
  ✗ [429] https://github.com/bdovaz | Failed: Network error: Too Many Requests
  ✗ [429] https://github.com/cgbosse | Failed: Network error: Too Many Requests
  ✗ [429] https://github.com/oxsecurity/megalinter/tree/main/docs/descriptors/editorconfig.md | Failed: Network error: Too Many Requests
  ✗ [429] https://github.com/oxsecurity/megalinter/tree/main/docs/descriptors/json_jsonlint.md | Failed: Network error: Too Many Requests
  ✗ [429] https://github.com/oxsecurity/megalinter/blob/main/docs/assets/images/GitHubCommentReporter.jpg?raw=true%3E | Failed: Network error: Too Many Requests
  ✗ [429] https://github.com/terraform-linters/tflint | Failed: Network error: Too Many Requests
  ✗ [429] https://github.com/oxsecurity/megalinter/tree/main/docs/descriptors/vbdotnet_dotnet_format.md | Failed: Network error: Too Many Requests
  ✗ [429] https://github.com/oxsecurity/megalinter/tree/main/docs/descriptors/go.md | Failed: Network error: Too Many Requests
  ✗ [429] https://github.com/oxsecurity/megalinter/tree/main/docs/config-postcommands.md | Failed: Network error: Too Many Requests
  ✗ [429] https://github.com/oxsecurity/megalinter/tree/main/docs/descriptors/html_htmlhint.md | Failed: Network error: Too Many Requests
  ✗ [429] https://github.com/super-linter/super-linter/pulls?q=is%3Apr+is%3Aclosed+author%3Anvuillam+review%3Aapproved | Failed: Network error: Too Many Requests

....

  📝 Summary
  ---------------------
  🔍 Total.........2290
  ✅ Successful....1441
  ⏳ Timeouts.........0
  🔀 Redirected.......0
  👻 Excluded.......425
  ❓ Unknown..........0
  🚫 Errors.........424
```

### PR DESCRIPTION
**Pull request by Techassi**
Fixes #1340

### CODE REVIEW

**Comment by Techassi** [comment]
How would such a test look like? Do we assert on the correct accepted status codes after merging the CLI values with the config file values?

**Comment by mre** [comment]
Sure, just something simple like https://github.com/Techassi/lychee/pull/1.

**Comment by mre** [comment]
Thanks for fixing the clippy error. 👍

**Comment by Techassi** [comment]
Oh I wanted to include the serde support :/

**Pull request merged**
