### PR TITLE
ci: fix missing permissions for uploading release assets

### PR DESCRIPTION
**Pull request by askalski85**
Dear @mre ,
I've noticed the release workflow was not updated since long time and I think we are missing proper token permissions for uploading release assets. Please take a look and I hope you will like it.

Cheers,
Arek

### CODE REVIEW

**Comment by guimochila** [comment]
@mre could you have a look at this?

**Comment by askalski85** [comment]
build failure unrelated to changes 
```
     Checking lychee-lib v0.13.0 (/home/runner/work/lychee/lychee/lychee-lib)
error: matching over `()` is more explicit
   --> lychee-lib/src/types/input.rs:206:55
    |
206 |                         .process_read_dir(move |_, _, _, children| {
    |                                                       ^ help: use `()` instead of `_`: `()`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#ignored_unit_patterns
    = note: `-D clippy::ignored-unit-patterns` implied by `-D warnings`
    = help: to override `-D warnings` add `#[allow(clippy::ignored_unit_patterns)]`

error: could not compile `lychee-lib` (lib) due to previous error
warning: build failed, waiting for other jobs to finish...
error: could not compile `lychee-lib` (lib test) due to previous error
Error: The process '/home/runner/.cargo/bin/cargo' failed with exit code 101
```

**Comment by askalski85** [comment]
The clippy suggested solution does not work, I am not rust expert to catch that ;-)

```
error[E0308]: mismatched types
   --> lychee-lib/src/types/input.rs:206:49
    |
206 |                         .process_read_dir(move |(), (), (), children| {
    |                                                 ^^
    |                                                 |
    |                                                 expected `Option<usize>`, found `()`
    |                                                 expected due to this
    |
    = note:   expected enum `std::option::Option<usize>`
            found unit type `()`

error[E0308]: mismatched types
   --> lychee-lib/src/types/input.rs:206:53
    |
206 |                         .process_read_dir(move |(), (), (), children| {
    |                                                     ^^
    |                                                     |
    |                                                     expected `Path`, found `()`
    |                                                     expected due to this
```

I will revert the fix commit and add suppression for the clippy error.

**Comment by askalski85** [comment]
Suppression works, might be not a perfect solution but I can't really tell how to work around it better.

**Comment by mre** [comment]
Thanks!

**Pull request merged**
