### PR TITLE
Extend remap feature

### LINKED ISSUE #1129: remap - can it rewrite partial URLs?
I have a list of URLs: 

```
https://docs.lakefs.io/integrations/distcp.html
https://docs.lakefs.io/howto/import.html#working-with-imported-data
https://docs.lakefs.io/howto/garbage-collection-committed.html
```

I want to test these URLs against my local build of the docs site (at `file:///Users/rmoff/git/lakeFS/docs/_site/`). This works using `sed`: 

```
sed 's/https:\/\/docs.lakefs.io/file:\/\/\/Users\/rmoff\/git\/lakeFS\/docs\/_site/' /tmp/list.txt | \
  lychee --dump -
file:///Users/rmoff/git/lakeFS/docs/_site/integrations/distcp.html
file:///Users/rmoff/git/lakeFS/docs/_site/howto/import.html#working-with-imported-data
file:///Users/rmoff/git/lakeFS/docs/_site/howto/garbage-collection-committed.html
```

I thought that remap could do this more elegantly for me, but whilst it remaps the base URL it ignores the rest of the mapped URL: 

```
lychee --remap 'https://docs.lakefs.io/ file:///Users/rmoff/git/lakeFS/docs/_site' --dump /tmp/list.txt
file:///Users/rmoff/git/lakeFS/docs/_site
file:///Users/rmoff/git/lakeFS/docs/_site
file:///Users/rmoff/git/lakeFS/docs/_site
```

Am I misunderstanding remap, or just using it incorrectly? 

thanks!

### PR DESCRIPTION
**Pull request by mre**
Extend support for remapping
    
This adds support for partial remaps and
capture groups to the remap feature.
    
Fixes #1129

### CODE REVIEW

**Comment by mre** [comment]
@rmoff, can you give that one a shot and report back if it works for you? You'd have to compile lychee from this branch.

**Comment by kemingy** [comment]
Hi @mre thanks for this awesome feature. I'm facing a similar issue. I need to remap:

```diff
- file:///home/docs/pages/frameworks/mosec
+ file:///home/docs/pages/frameworks/mosec.mdx
# exclude file:///home/docs/pages/frameworks/graph.png
```

I have verified that this PR works for me.

**Comment by mre** [comment]
Thanks for the feedback. I will update the lychee docs website before I merge this.

**Comment by kemingy** [comment]
Hi @mre, I'm using this feature in the GitHub Actions. It seems the lychee-action doesn't support installation from source or nightly build. Do you mind creating a new release? Thanks a lot.

**Comment by mre** [comment]
Oh, of course. Will do. 👍

**Comment by mre** [comment]
Supporting nightly builds is a great idea. I'd merge that if you want to add it, but I can't remember if we even build nightly versions right now.

**Comment by kemingy** [comment]
> Supporting nightly builds is a great idea. I'd merge that if you want to add it, but I can't remember if we even build nightly versions right now.

Sure, I will create a PR for the nightly release.

**Pull request merged**
