### PR TITLE
Regression: Ignore invalid URLs (fixes #562)

### LINKED ISSUE #562: v0.9.0 regression: Unknown schemes throw errors
We have some code blocks in our docs which contain schemes unknown to lychee but valid for other applications. Those were gracefully ignored before and now throw errors, e.g.:
```
Error: R] librespot:///usr/bin/librespot?name=mySpotify&devicename=SnapcastSpotify&disable_audio_cache=true | The given URI is invalid: librespot:///usr/bin/librespot?name=mySpotify&devicename=SnapcastSpotify&disable_audio_cache=true
Error: R] pipe:///tmp/mpd.fifo?name=myMPD&mode=read | The given URI is invalid: pipe:///tmp/mpd.fifo?name=myMPD&mode=read
Error: R] airplay:///usr/local/bin/shairport-sync?name=myAirport&devicename=SnapcastAirport&params=--configfile=/usr/local/etc/shairport-sync.conf | The given URI is invalid: airplay:///usr/local/bin/shairport-sync?name=myAirport&devicename=SnapcastAirport&params=--configfile=/usr/local/etc/shairport-sync.conf
Error: R] pipe:///tmp/mopidy.fifo?name=myMopidy&mode=read | The given URI is invalid: pipe:///tmp/mopidy.fifo?name=myMopidy&mode=read
```
Since lychee anyway catches those URLs by itself, while they are no explicit links, it doesn't make much sense to fail on them: "This looks like an URL, let me check it... but doesn't look like a valid URL, let me throw an error" 😃.

### PR DESCRIPTION
**Pull request by mre**
With the refactoring the URL checking as a workaround for the upstream
reqwest panic on invalid URLs, we introduced a regression, which caused
unsupported URL schemes to show up as errors in the lychee output.

This commit changes the behavior such that invalid schemes get ignored
again by making a differentiation between truly invalid URIs which would make
reqwest panic, and ones which are valid but just not handled by reqwest.
The check was moved to `check_website` such that the invalid URIs would
not be checked three times in a loop before erroring out.

### CODE REVIEW

**Comment by MichaIng** [comment]
Looks good. Would it be possible to have html5gum, respectively the document parser, skipping those in the first place, so that unsupported schemes are not even caught as URIs?

**Comment by mre** [comment]
Technically yes. We could move the url parsing into the extractors. However this would closely couple extraction and link creation. Also, I do like the fact that ignored links get listed to indicate to the user that they were found but aren't supported yet.

**Comment by mre** [comment]
Gonna merge this. We can discuss further changes in a separate issue. For now I'm in interested in restoring the old behavior.

**Comment by MichaIng** [comment]
> Technically yes. We could move the url parsing into the extractors.

The question is how the extractor detects an URL in first place, probably that can be narrowed to include only supported schemes so that there is no "additional" parsing required.

> Also, I do like the fact that ignored links get listed to indicate to the user that they were found but aren't supported yet.

That is an argument, also when users compare the effectiveness of link checkers by comparing the detected URL counts 🙂.

**Comment by mre** [comment]
> The question is how the extractor detects an URL in first place, probably that can be narrowed to include only supported schemes so that there is no "additional" parsing required.

The parsing will be done anyway. The extractors will fetch stuff that looks like links either way, the only difference is that we would do the parsing sooner before sending it to reqwest. There is an overhead to sending it to reqwest, although I doubt it would be measurable. On the other hand, we'd have to maintain some sort of "allow list" for schemes that we support. We introduced a small check for "http" and "https" in this PR, but in general I'd prefer to avoid that because we'd get immediate support for new formats that reqwests (or any other HTTP client we might add in the future) supports in the future without having to touch the lychee code. 😉

**Comment by MichaIng** [comment]
> On the other hand, we'd have to maintain some sort of "allow list" for schemes that we support.

But we have that now as well... ah, further reading 🙂. But we had such before this PR as well, isn't it, or how were unsupported schemes ignored before?

If it is up to reqwest only and wouldn't require any changes in lychee code to support further protocols, then I agree it is best to simply send to reqwest what we get and find a way or ask upstream for a return/error code when the protocol/scheme is not supported, so that we can ignore/show as excluded those URLs instead of printing it as error.

**Comment by mre** [comment]
They do send an error (unless they panic before, haha 😆). That's how we find out that a URI is not supported right now. So the only thing we might want to do is silently hide the unsupported links instead of denoting them as ignored; it's more of an aesthetic question. Are you concerned about the visual noise? 🤔

**Comment by lebensterben** [comment]
they'd better be shown as unsupported. this helps to detect typos such as htp://example.com

**Comment by MichaIng** [comment]
> They do send an error (unless they panic before, haha 😆). That's how we find out that a URI is not supported right now.

But we currently do the validation our end as well to prevent panics?
```
// It is exactly the same check that reqwest runs internally, but unfortunately
// it `unwrap`s (and panics!) instead of returning an error, which we could handle.
```

However, it makes sense then to keep things as they are and hope for soon graceful error handling and response in reqwest so that we can pass all URIs without any validation and handle it as invalid or unsupported based on error response.

> they'd better be shown as unsupported. this helps to detect typos such as htp://example.com

Another good argument 👍.

**Comment by mre** [comment]
> But we currently do the validation our end as well to prevent panics?

Yeah we only do it for avoiding panics. 😊

**Pull request merged**
