### PR TITLE
WIP: Fix publish workflow

### PR DESCRIPTION
**Pull request by dblock**
Attempts at fixing the publish workflow.

### CODE REVIEW

**Review by lebensterben — APPROVED** [review]

**Comment by dblock** [comment]
@lebensterben Hit approve on the workflow so we can see it go to green?

**Comment by lebensterben** [comment]
@dblock 
I'm not a maintainer. It need a maintainer to start workflows for first-time contributors.

**Comment by mre** [comment]
About point no. 1, clippy wants you to write it like this:

```rust
    matches!(
        (attr_name, elem_name),
        ("href" | "src" | "srcset" | "cite", _) | ("data", "object") | ("onhashchange", "body")
```

I fixed this and other linting issues in #306 with https://github.com/lycheeverse/lychee/pull/306/commits/c5d75447cad2a665e9bb126f2a04090ebd6df7f5.
You can cherry-pick that commit if you like.

**Comment by dblock** [comment]
> About point no. 1, clippy wants you to write it like this:
> 
> ```rust
>     matches!(
>         (attr_name, elem_name),
>         ("href" | "src" | "srcset" | "cite", _) | ("data", "object") | ("onhashchange", "body")
> ```
> 
> I fixed this and other linting issues in #306 with [c5d7544](https://github.com/lycheeverse/lychee/commit/c5d75447cad2a665e9bb126f2a04090ebd6df7f5).
> You can cherry-pick that commit if you like.

Oh I see.

Let's fix the build first. What do we do about the publishing checker?

**Comment by mre** [comment]
> What do we do about the publishing checker?

I don't think `cargo-publish-all` is a good solution for this. It hasn't seen any updates in two years and there are issues similar to the one you described (https://gitlab.com/torkleyy/cargo-publish-all/-/issues/3).
It's also a third-party solution and I think we should focus on core tools like cargo in that case.

My plan is to cherry-pick some changes from this PR and then I would like to close the PR and publish a new version of lychee, which should make future builds green for the time being. In the long run I'd very much like a solution that doesn't require publishing lychee-lib if there's an API change. #305

**Comment by mre** [comment]
0.7.1 is out. 🥳 
@dblock and @lebensterben thanks for your contributions. I'll close this as the CI pipeline is green again. We can talk about workflow improvements in #305.

**Comment by dblock** [comment]
> 0.7.1 is out. 🥳
> @dblock and @lebensterben thanks for your contributions. I'll close this as the CI pipeline is green again. We can talk about workflow improvements in #305.

So the problem with this green pipeline is that it checks publication of lychee-bin against the *previous* version of lychee. So it's fake green. I got a fix coming.

**Pull request closed without merging**
