### PR TITLE
Harmonizes naming pattern of pre-built binaries and unlocks latest permalink

### LINKED ISSUE #1463: ci: inconsistent naming of gh release assets
Hi,
I'm in the process of proposing a simpler and cross platform approach to enable a lychee pre-commit hook which uses the pre-built binaries. For that to work cross platform, the filenames of the release assets need a fix. `linux` assets are all consistent but differ from `macos` and `windows` assets.

I prepared [a PR](https://github.com/lycheeverse/lychee/pull/1464) which renames the windows and mac assets to match the linux pattern. I figured while I'm at it, I could also strip the version from the filenames. This unlocks the possibility to offer a permalink to the latest release, without having to know the version: 

https://docs.github.com/en/repositories/releasing-projects-on-github/linking-to-releases#linking-to-the-latest-release

This makes it trivial for downstream consumers to automate the download of the latest binary (after weighting the pro's and con's of course 😉).

### PR DESCRIPTION
**Pull request by axel-kah**
This closes #1463

### CODE REVIEW

**Comment by mre** [comment]
Interesting. 

We probably also need to update the Docker images [here](https://github.com/lycheeverse/lychee/blob/master/Dockerfile-CI.Dockerfile) and [here](https://github.com/lycheeverse/lychee/blob/master/Dockerfile-CI.alpine.Dockerfile) as well as create a PR for the lychee-action [here](https://github.com/lycheeverse/lychee-action/blob/master/action.yml).

**Comment by axel-kah** [comment]
- [x] Dockerfiles
- [x] Nightly assets
- [x] sync with lychee action (https://github.com/lycheeverse/lychee-action/pull/233)

**Comment by axel-kah** [comment]
The test fails seem to be unrelated to my changes. Their implementation contains remarks about flakyness. Maybe increasing the number of re-tries or adding a delay in between would help to reduce the ci-noise.

**Comment by mre** [comment]
Thanks @axel-kah! The code looks fine. I didn't find a great way to test it, but we'll give it a shot with the next release. 👍

**Comment by axel-kah** [comment]
Sweet! Any idea when that will be (ballpark)?

**Comment by mre** [comment]
We got some issues with the change. Follow https://github.com/lycheeverse/lychee-action/issues/232 and https://github.com/lycheeverse/lychee-action/pull/234 for updates.

**Pull request merged**
