### PR TITLE
Add interesting projects who use lychee

### PR DESCRIPTION
**Pull request by thomas-zahner**
Today I encountered some interesting projects using lychee

### CODE REVIEW

**Comment by mre** [comment]
Awesome list!
Let's add Gradle as well: https://github.com/gradle/gradle/blob/master/.github/workflows/check-markdown-links.yml

**Comment by thomas-zahner** [comment]
Ah didn't know that :+1:

**Comment by thomas-zahner** [comment]
I've added the link just to the repo, not the full path where lychee is used for consistency. Would you prefer all links pointing to a lychee config or the workflow file so one can quickly see how lychee is used in that project?

Also the links are getting more numerous in the README (and maybe other places as well?). Maybe we could consider adding lychee's GitHub action to lychee? Maybe something equivalent to `lychee --exclude-path benches --exclude-path fixtures . --verbose`

**Review by mre — APPROVED** [review]

**Comment by mre** [comment]
Great list, thanks!

I like the idea of using lychee-action and the proposed config. Let's do that to in a separate pull request. 

I think linking to the repos makes sense as the config files could be renamed. We could have a separate config showcase on the lychee website at some point.

**Pull request merged**
