### PR TITLE
feat: replace url with ada_url crate

### PR DESCRIPTION
**Pull request by anonrig**
Pretty much work in progress. There are some missing APIs on Ada, which I'll add, but one potential blocker is how the codebase is inter-coupled with reqwest::Url, and how reqwest forces to use Url struct.

Any feedback is appreciated.

### CODE REVIEW

**Comment by mre** [comment]
Thanks for the PR.

It would also be nice to add a crate feature to be able to switch the URL implementation at compile-time. This would make it possible to compare both implementations.

We could do so, by introducing a `lychee::Url` trait and implementing it for both, the current URL and `ada_url::URL`. 

With regards to `reqwest`, it would be nice to have a similar feature, but that would have to be contributed upstream and progress is pretty slow in `reqwest` from my experience. It would be nice to [avoid mixing URL parsers](https://daniel.haxx.se/blog/2022/01/10/dont-mix-url-parsers/), though, as you are aware.

Interested to hear what you think. Maybe I'm missing an alternative option here.

**Comment by anonrig** [comment]
Hey @mre,

I used a different API of `reqwest` that doesn't take Url, but takes a string and fixed that issue. There are only 2 remaining errors exist, which requires a little bit more time, but overally the progress continues.

> It would also be nice to add a crate feature to be able to switch the URL implementation at compile-time. This would make it possible to compare both implementations.

Unfortunately, I don't have any time to add this, but feel free to take over this pull request when I fixed ada related issues.

> With regards to reqwest, it would be nice to have a similar feature, but that would have to be contributed upstream and progress is pretty slow in reqwest from my experience. It would be nice to [avoid mixing URL parsers](https://daniel.haxx.se/blog/2022/01/10/dont-mix-url-parsers/), though, as you are aware.

Technically we are not mixing URL parsers. Both parsers are WHATWG URL specification compliant. Unfortunately, `url` crate does not seem to be up to date with the recent changes on the specification. On the other hand, Ada follows all web-platform-tests changes and implements them in less than 24 hours.

Remaining errors:

```
➜  lychee git:(wip-ada-url) ✗ cargo build
   Compiling lychee-lib v0.13.0 (/Users/yagiz/Developer/lychee/lychee-lib)
error[E0599]: no method named `join` found for reference `&ada_url::Url` in the current scope
  --> lychee-lib/src/types/base.rs:25:38
   |
25 |             Self::Remote(url) => url.join(link).ok(),
   |                                      ^^^^ method not found in `&Url`

error[E0599]: no method named `cannot_be_a_base` found for struct `ada_url::Url` in the current scope
  --> lychee-lib/src/types/base.rs:67:20
   |
67 |             if url.cannot_be_a_base() {
   |                    ^^^^^^^^^^^^^^^^ method not found in `Url`

For more information about this error, try `rustc --explain E0599`.
error: could not compile `lychee-lib` (lib) due to 2 previous errors
```

**Comment by anonrig** [comment]
Ok build passes, but 2 tests fail. Would you like to identify the errors? @mre

**Comment by mre** [comment]
Awesome progress! I didn't get the chance to run it locally and do a little benchmark, but it's on my list. Just wanted to let you know.

Speaking of benchmarks, there is one as part of the repo. From the `benches` folder:

```
cargo bench -p benches
```

**Comment by anonrig** [comment]
@mre I'm currently running on `ada-url` `main` branch, but locally all tests pass. I'll release v2.0 soon with `no-std` support of the crate.

**Comment by anonrig** [comment]
I'm not sure the validity of the benchmarks or how much of the overall benchmark is spent on URL parsing, but using `cargo bench -p benches` I get around 7% improvement. Side note: URL parsing benchmarks show 3x improvement over `url`.


```
extract from large docs time:   [12.257 ms 12.312 ms 12.356 ms]
                        change: [-8.6041% -6.9133% -5.4985%] (p = 0.00 < 0.05)
                        Performance has improved.
```

**Comment by mre** [comment]
That's really good. Most of the time was probably spent elsewhere already (extraction). I did not expect that. Especially when handling local files, this can be of significant impact.

**Pull request closed without merging**
