### PR TITLE
Publish releases on crates.io

### PR DESCRIPTION
**Pull request by mre**
See #59 
Pipeline code taken from https://github.com/EmbarkStudios/tryhard/blob/main/.github/workflows/rust-ci.yml

### CODE REVIEW

**Comment by pawroman** [comment]
Have you thought about syncing git tag with Cargo crate version in `Cargo.toml`?

My worry is that the tags and version in `Cargo.toml` can get out of sync. At the very least, we should check if they are in sync before publishing.

**Comment by mre** [comment]
> Have you thought about syncing git tag with Cargo crate version in Cargo.toml?

Nope, but it's a great idea. Not sure how to do this, though. Are there any other projects that do that already that we can learn from?

**Comment by pawroman** [comment]
> Not sure how to do this, though. Are there any other projects that do that already that we can learn from?

I can do some research into it. Not a blocker for this PR though.

**Comment by mre** [comment]
Thanks, then I'll merge it.
I think I'll add support for binary releases to Github, too and then cut a new 0.4.0 release.

**Pull request merged**
