### PR TITLE
Handle relative links

### PR DESCRIPTION
**Pull request by mre**
WIP for #1296 and #1480

This just adds a failing test based on @nobkd's minimal repro.
I didn't fix the underlying issue.

### CODE REVIEW

**Comment by mre** [comment]
It doesn't run the failing test yet. See #1483.
The Docker build failure is unrelated.

**Comment by nobkd** [comment]
Might also be interesting. Not sure if this is maybe already used by lychee. :shrug:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base

**Comment by mre** [comment]
> Might also be interesting/relevant. Not sure if this is maybe already used by lychee. :man_shrugging:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base

Very interesting; I never heard of it.
The current implementation is pretty basic, and we don't use `<base>`. Looking at the docs, there seem to be quite a few different cases to be handled, so I'd like to postpone handling that for now. But thanks for the tip.

**Comment by mre** [comment]
Superseded by https://github.com/lycheeverse/lychee/pull/1489.

**Pull request closed without merging**
