### PR TITLE
Try to improve build times

### PR DESCRIPTION
**Pull request by mre**
Based on https://corrode.dev/blog/tips-for-faster-rust-compile-times/

### CODE REVIEW

**Comment by mre** [comment]
Results:
* First run: 3m 29s
* Second run: 1m 54s
* Third run: 1m 42s

Pretty good! Cached builds haven't been below 2 minutes in a while and are typically [hovering around 3m 30s](https://github.com/lycheeverse/lychee/actions/workflows/ci.yml?page=2&query=is%3Asuccess), so I call this an improvement, although I did not run exhaustive tests.

**Comment by MarcoIeni** [comment]
it seems that [rust-cache](https://github.com/Swatinem/rust-cache) automatically set CARGO_INCREMENTAL.
From the readme:
image

**Comment by mre** [comment]
Oh, I did not know that. Thanks for sharing!
Couldn't harm to explicitly add it, just in case we move to a different caching solution in the future (even though I doubt that will happen anytime soon; `rust-cache` is pretty awesome).

**Comment by MarcoIeni** [comment]
yeah, I just wanted to share this :)
Great article btw :)
I didn't know about cargo-features-manager

**Pull request merged**
