### PR TITLE
Add no check (dump links only) flag

### PR DESCRIPTION
**Pull request by pawroman**
I'm not very fixed on the flag's name, it's the best I could come up with after a few minutes of thinking about it. Suggestions for different names welcome!

### CODE REVIEW

**Comment by pawroman** [comment]
@mre any thoughts on this so far?

**Comment by mre** [comment]
@pawroman apart from the `README.md` usage update (great feature BTW) this would be ready to merge from my side.

**Comment by pawroman** [comment]
> @pawroman apart from the README.md usage update (great feature BTW) this would be ready to merge from my side.

Fixed. I have also reworded the help text a little tiny bit for clarity.

**Comment by pawroman** [comment]
Actually, I'm having some second thoughts about the help text.

With current implementation, the `--exclude`s have no effect on the dumped links. 

@mre do you think that we should:
1. Leave it as is
2. Change the implementation to respect excludes etc
3. Adjust the help text to say that it's going to dump all links found in inputs (the exclude flags not affecting the output)
4. Mark each link in the output somehow, similar to `--verbose` (indicating which links would be skipped)

**Comment by mre** [comment]
I'd go with option 2: Change the implementation to respect excludes.
The reasoning is that I think of the command as a "dry-run". If you agree, perhaps we should rename the flag to `--dry-run` to make it a little clearer?
Alternatively if our main goal is to test the link detection with that flag, we could skip the exclude parts and perhaps name the flag `--dump` or `--dump-links`.

**Comment by mre** [comment]
Update: I moved the `exclude` behavior into a separate mod called `filter`. With that it should be a little easier to remove the excluded links before dumping them.

**Comment by pawroman** [comment]
> Thanks. Haven't looked at it yet, but my suspicion is that it's because we do the parsing before the rejection of mail addresses in general.

Thanks for the heads up. Once I have some spare time, I will re-visit this PR with that in mind.

**Comment by mre** [comment]
Renamed the flag to `--dump` now. Also removed the banner as it was printed to `stdout` on my machine and other Unix tools also don't have any header output for similar cases AFAIK.  It looks a bit cleaner to me.

What's missing is the exclude part.

**Comment by mre** [comment]
> What's missing is the exclude part.

Added that now.

**Pull request merged**
