### PR TITLE
Remove srcset attribute from list of "link" attrs

### LINKED ISSUE #390: Lychee treats srcSet attribute as single URL
lychee incorrectly parses srcSet into a single URL which fails to resolve to any filename.

```
Errors in platforms/apple/guides/macos/enriching-events/context/index.html
✗ file:///home/markus/projects/sentry-docs/public/static/1bd990e15ff62d8c08f68a249fa0face/5a46d/additional_data.png%20300w,/static/1bd990e15ff62d8c08f68a249fa0face/0a47e/additional_data.png%20600w,/static/1bd990e15ff62d8c08f68a249fa0face/7321b/additional_data.png%201184w (Cannot find file file:///home/markus/projects/sentry-docs/public/static/1bd990e15ff62d8c08f68a249fa0face/5a46d/additional_data.png%20300w,/static/1bd990e15ff62d8c08f68a249fa0face/0a47e/additional_data.png%20600w,/static/1bd990e15ff62d8c08f68a249fa0face/7321b/additional_data.png%201184w)
```

the corresponding HTML:

```
  <img class="gatsby-resp-image-image" alt="Custom contexts as viewed on the Additional Data section of an event" title="Custom contexts as viewed on the Additional Data section of an event" src="/static/1bd990e15ff62d8c08f68a249fa0face/7321b/additional_data.png" srcSet="/static/1bd990e15ff62d8c08f68a249fa0face/5a46d/additional_data.png 300w,/static/1bd990e15ff62d8c08f68a249fa0face/0a47e/additional_data.png 600w,/static/1bd990e15ff62d8c08f68a249fa0face/7321b/additional_data.png 1184w" sizes="(max-width: 1184px) 100vw, 1184px" style="width:100%;height:100%;margin:0;vertical-align:middle;position:absolute;top:0;left:0" loading="lazy"/>
```

### PR DESCRIPTION
**Pull request by untitaker**
Fix #390

### CODE REVIEW

**Comment by mre** [comment]
Oh yeah that's it! Can we add a test as well?

**Comment by untitaker** [comment]
@mre what kind of test are you looking for and where would I put one? I think a unittest is not very useful.

**Comment by mre** [comment]
I've added a test to the branch we can work with. It's a very simple thing in the extractor. It's failing right now as it will not detect the links from the `srcSet`. Is that how we expected it to work? Probably we should change it so that it also finds the remaining links right?

**Comment by mre** [comment]
Just pushed to your branch, hope that's fine. 😅

**Comment by mre** [comment]
I think supporting the links from `srcSet` will be tricky. It is detected as one string and passed to linkify. :/

**Comment by mre** [comment]
I've disabled them for now. From my side this is good to go. It's not perfect but it's definitely an improvement. @untitaker what do you say?

**Comment by untitaker** [comment]
i'm writing srcset support right now, give me a second

**Comment by untitaker** [comment]
That should be it!

**Comment by mre** [comment]
Nicely done. Thanks! 🚀

**Pull request merged**
