### PR TITLE
Try to prevent flaky tests

### PR DESCRIPTION
**Pull request by mre**
Moves from example.org to example.com
to see if that makes testing results more consistent

### CODE REVIEW

**Comment by mre** [comment]
Looks like example.com is slightly more permissive than example.org or at least the two domains are configured differently at least. I'm okay with merging this.

**Comment by mre** [comment]
In the long run we should still use a mock server, but this is good enough to unblock some PRs.

**Comment by lebensterben** [comment]
You may also be interested in https://github.com/nextest-rs/nextest to figure out flaky tests.

**Comment by mre** [comment]
@lebensterben feel free to rebase your pull requests on `master` to see if this resolves our issues. 😃

**Pull request merged**
