### PR TITLE
Exclude URLs ending with xmlrpc.php

### LINKED ISSUE #1210: Ignore checks to known XML-RPC endpoints
Ignore checks to known XML-RPC endpoints to prevent false positives.
These endpoints only accept POST requests AFAICT.

Example:

```md
✗ [405] https://www.doppelgaenger.io/xmlrpc.php | Failed: Network error: Method Not Allowed
```

Practically, that means adding `xmlrpc.php` to the list of false-positive patterns:

https://github.com/lycheeverse/lychee/blob/f6f7cfb5e5ea1be5388f5a73675ebab1a1d287ba/lychee-lib/src/filter/mod.rs#L33-L41

Pull requests welcome.

### PR DESCRIPTION
**Pull request by aj-stein-nist**
Closes #1210.

### CODE REVIEW

**Comment by mre** [comment]
Looks good. I'd merge it. Why is it a draft? 😅

**Comment by aj-stein-nist** [comment]
> Looks good. I'd merge it. Why is it a draft? 😅

It was late and I hadn't test it manually, is there a good way to test this and to unit tests or something?

**Comment by mre** [comment]
The exclusion logic is already covered by a unit test. Maybe you want to add one for this pattern specifically, but it's also fine if not. 🙃

**Comment by aj-stein-nist** [comment]
I marked it as ready then, sounds good. I forgot about October and Octoberfest. 😆

**Comment by mre** [comment]
Thanks for your contribution. 🌟

**Pull request merged**
