### PR TITLE
test: fail when interpreting md footnote as link

### PR DESCRIPTION
**Pull request by jan-ferdinand**
#1409

### CODE REVIEW

**Comment by mre** [comment]
Uhm... I didn't want to close this?

**Comment by mre** [comment]
Reopening

**Comment by mre** [comment]
I think I locked myself out of this one.  Looks like I don't have permission to push to your fork @jan-ferdinand. 😅

**Comment by mre** [comment]
I don't know how exactly it worked either, but I think I tried to update your branch with my fix and that failed. Somehow the changeset was empty and that auto-closed the pull request. No idea.

Anyhow, after I realized my mistake, I created this new branch with the fix: https://github.com/lycheeverse/lychee/pull/1479
I think it's ready to be merged to get the bug fixed.

------


Side note for the future: it's better to create a new branch on your fork, which describes the problem instead of using `master`. So for example `jan-ferdinand:footnote-link` or so. This makes it a little easier to see which branch I'm on when I'm working from the commandline and also keeps the changes in this new branch separate from `master`, which is usually a clone of the upstream master. It would not have prevented my mistake, though; just best-practice.

**Comment by jan-ferdinand** [comment]
Makes perfect sense. :+1: Next time. :slightly_smiling_face:

**Pull request closed without merging**
