### PR TITLE
chore(ci)!: update github actions

### PR DESCRIPTION
**Pull request by lebensterben**
Most changes are merely on version changes, log messages and comments, and structuring.

The only significant change is that `actions/upload-release-asset@v1` is deprecated and its replacement, i.d. `softprops/upload-release-asset@v1` has rather different interface.

### CODE REVIEW

**Comment by mre** [comment]
Thanks, looks good.
CI seems to be failing because `cargo@v2` doesn't exist. Guess you have to change that back to v1.

**Comment by lebensterben** [comment]
caught a bug in actions-rs/toolchain...
it only recognizes rust-toolchain, not rust-toolchain.toml

**Comment by lebensterben** [comment]
seems like action-rs/toolchain is not actively maintained. I'm going to add back the explicit toolchain argument for the moment.

**Comment by lebensterben** [comment]
is there anyway to test the "Release" action? That's where the major changes occured.

**Comment by mre** [comment]
I don't know of a good way to test the release action. (Which doesn't mean that there is no good way.)
The only way I can think of is to comment out `upload-release-asset` and [replace it with a `tmate` session](https://github.com/mxschmitt/action-tmate).
Speaking of which, where is the source code for `softprops/upload-release-asset`? I thought it would be at https://github.com/softprops/upload-release-asset, but it isn't. Also can't find it on the marketplace.

**Comment by lebensterben** [comment]
sorry, it should be https://github.com/softprops/action-gh-release

**Comment by mre** [comment]
@lebensterben can you rebase on top of `master`? I might some CI improvements to speed up the builds.

**Comment by lebensterben** [comment]
I spotted some errors when rebasing. I will address that first

**Comment by lebensterben** [comment]
I will divide this to smaller PRs

**Comment by mre** [comment]
Thanks so much.

**Pull request closed without merging**
