### PR TITLE
Add different verbosity levels

### PR DESCRIPTION
**Pull request by mre**
More granular verbosity levels have been asked
for repeatedly.
To enable that we're moving to [env_logger] and [clap-verbosity-flag]
to provide more flexible verbosity settings.

Also tackles #661, #709.
Lays the groundwork for tackling #268 and #704.

https://github.com/rust-cli/env_logger
https://github.com/clap-rs/clap-verbosity-flag

### CODE REVIEW

**Comment by mre** [comment]
If someone finds the time I'd love to get a review to avoid regressions.

**Comment by tooomm** [comment]
Is there some brief explanation somewhere? Which information do the various level add (v) or remove (q)?

**Comment by mre** [comment]
At the moment it's pretty basic:

* Verbose mode (`-v`) prints `data` URLs and false-positive URLs (e.g. example.com, which is an IANA reserved domain).
* Normal mode (without any `-v`) skips those.

That's it.
We could add something to the docs, but I don't know if it's worth it. Suggestions welcome.

**Comment by tooomm** [comment]
Hmm, but what will `-vv` print then? Or `-vvv`?

**Pull request merged**
